version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      # ZOOKEEPER_SYNC_LIMIT: 2
    healthcheck:
      test: echo srvr | nc zookeeper 2181 || exit 1
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 6
    networks:
      - cdc-bp

    kafka:
      image: confluentinc/cp-kafka:7.4.0
      container_name: kafka
      hostname: kafka
      ports:
        - "9092:9092"
        - "9101:9101"
        - "29092:29092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS:  PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_AUTOCREATE_TOPICS_ENABLE: "true"
        KAFKA_JMX_PORT: 9101
        KAFKA_JMX_HOSTNAME: localhost

      healthcheck:
        test: echo "describe topics" | nc kafka 9092 || exit 1
        start_period: 15s
        interval: 5s
        timeout: 15s
        retries: 6
      networks:
        - cdc-bp
    
networks:
  cdc-bp:
    name: cdc-bp
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: